### ISSUE TITLE
Create Swift RSocket Exceptions 

### ISSUE THREAD

**Issue by Samer-Abdulaziz** [rsocket/rsocket-swift#8]
Create Rsocket exception in Swift

## Motivation

As we are starting the rocket-swift project we will need a generic  way to throw  rsocket exceptions in swift 
## Desired solution

use swift to create the rsocket exception using swift 5 error handling

**Comment by dnadoba** [comment]
[Exceptions](https://developer.apple.com/documentation/foundation/nsexception) are usually not used in Swift but [Errors](https://developer.apple.com/documentation/swift/error).

I think especially after PR #48 we have a good solution for RSocket Errors and I will close this issue. 
Feel free to reopen if you disagree.
